apiVersion: v2
name: chrono-reaper
description: |
  A Kubernetes operator that automatically deletes resources annotated with
  wenisch.tech/ttl when the specified UTC timestamp has passed.
type: application
version: 0.0.6
appVersion: "0.0.6"
keywords:
  - kubernetes
  - operator
  - ttl
  - garbage-collection
home: https://github.com/wenisch-tech/ChronoReaper
sources:
  - https://github.com/wenisch-tech/ChronoReaper
maintainers:
  - name: wenisch-tech
    url: https://wenisch.tech
